insert into part(name, quantity, isMustHave) values ('Mother Board', 12, true);
insert into part(name, quantity, isMustHave) values ('Mother Board - Gaming', 2, true);
insert into part(name, quantity, isMustHave) values ('Sound Card', 22, false);
insert into part(name, quantity, isMustHave) values ('Processor - 4 Threads', 7, true);
insert into part(name, quantity, isMustHave) values ('Processor - 6 Threads', 4, true);
insert into part(name, quantity, isMustHave) values ('Processor - 8 Threads', 1, true);
insert into part(name, quantity, isMustHave) values ('Processor - 16 Threads', 2, false);
insert into part(name, quantity, isMustHave) values ('Graphic Card - 2GB', 5, false);
insert into part(name, quantity, isMustHave) values ('Graphic Card - 4GB', 5, false);
insert into part(name, quantity, isMustHave) values ('Graphic Card - 8GB', 5, false);
insert into part(name, quantity, isMustHave) values ('Drive - HDD 1TB', 7, true);
insert into part(name, quantity, isMustHave) values ('Drive - HDD 2TB', 4, false);
insert into part(name, quantity, isMustHave) values ('Drive - HDD 4TB', 2, false);
insert into part(name, quantity, isMustHave) values ('Drive - SSD 128GB', 4, true);
insert into part(name, quantity, isMustHave) values ('Drive - SSD 256GB', 3, true);
insert into part(name, quantity, isMustHave) values ('Drive - SSD 512GB', 1, true);
insert into part(name, quantity, isMustHave) values ('Drive - SSD 1TB', 1, false);
insert into part(name, quantity, isMustHave) values ('DVD-RW Drive', 5, false);
insert into part(name, quantity, isMustHave) values ('Floppy Drive', 1, false);
insert into part(name, quantity, isMustHave) values ('Cooller - Water Coller', 12, false);
insert into part(name, quantity, isMustHave) values ('Cooller - Processor Coller', 22, true);
insert into part(name, quantity, isMustHave) values ('RAM 2x4GB', 6, true);
insert into part(name, quantity, isMustHave) values ('RAM 2x8GB', 12, false);
insert into part(name, quantity, isMustHave) values ('RAM 2x16GB', 2, false);
insert into part(name, quantity, isMustHave) values ('RAM 1x4GB', 7, false);
insert into part(name, quantity, isMustHave) values ('RAM 1x8GB', 11, true);
insert into part(name, quantity, isMustHave) values ('RAM 1x16GB', 5, false);
insert into part(name, quantity, isMustHave) values ('Case - Some Brand', 1, true);
insert into part(name, quantity, isMustHave) values ('Case - Solid Gear', 12, true);
insert into part(name, quantity, isMustHave) values ('Mouse - A4Tech X7', 5, false);
insert into part(name, quantity, isMustHave) values ('Mouse - Logitech', 45, false);
insert into part(name, quantity, isMustHave) values ('KeyBoard - Corsair X70', 4, false);
insert into part(name, quantity, isMustHave) values ('KeyBoard - Logitech', 13, true);
insert into part(name, quantity, isMustHave) values ('RGB Strip', 11, false);
insert into part(name, quantity, isMustHave) values ('CardReader - Logitech', 7, false);
insert into part(name, quantity, isMustHave) values ('Power Supply - 650W', 13, true);
insert into part(name, quantity, isMustHave) values ('Power Supply - 850W', 11, true);
insert into part(name, quantity, isMustHave) values ('Power Supply - 1200W', 1, true);
